// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickBite.Data;

namespace QuickBite.Data.Migrations
{
    [DbContext(typeof(QuickBiteContext))]
    partial class QuickBiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("QuickBite.Pages.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnName("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A scrumptious, healthy sandwich with avocado, a protein of your choice and salad",
                            ImageName = "sandwich.jfif",
                            Name = "Avocado sandwich",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A delicious salad with veggies of your choice, tossed to perfection",
                            ImageName = "salad.jfif",
                            Name = "Salad",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Houmous, olives, tahinina and veggies of your choice in a delicious wrap",
                            ImageName = "wrap.jfif",
                            Name = "Houmous wrap",
                            Price = 5.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
